import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createOrder: "Create Order",
  AppStrings.itemName: "Item Name",
  AppStrings.enterItemName: "Enter item name",
  AppStrings.pleaseEnterItemName: "Please enter item name",
  AppStrings.pvdColor: "PVD Color",
  AppStrings.enterPVDColor: "Enter pvd color",
  AppStrings.pleaseEnterPVDColor: "Please enter pvd color",
  AppStrings.quantity: "Quantity",
  AppStrings.enterQuantity: "Enter quantity",
  AppStrings.pleaseEnterQuantity: "Please enter quantity",
  AppStrings.size: "Size",
  AppStrings.enterSize: "Enter size",
  AppStrings.pleaseEnterSize: "Please enter size",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "Enter ok pcs.",
  AppStrings.pleaseEnterOkPcs: "Please enter ok pcs.",
  AppStrings.rejected: "Rejected",
  AppStrings.enterRejected: "Enter rejected",
  AppStrings.pleaseEnterRejected: "Please enter rejected",
  AppStrings.pending: "Pending",
  AppStrings.enterPending: "Enter pending",
  AppStrings.pleaseEnterPending: "Please enter pending",
  AppStrings.orderDetails: "Order Details",
  AppStrings.woProcess: "W/O Process",
  AppStrings.enterWOProcess: "Enter w/o process",
  AppStrings.pleaseEnterWOProcess: "Please enter w/o process",
  AppStrings.partyName: "Party Name",
  AppStrings.enterPartyName: "Enter party name",
  AppStrings.pleaseEnterPartyName: "Please enter party name",
  AppStrings.searchParty: "Search party",
  AppStrings.selectParty: "Select party",
  AppStrings.pleaseSelectParty: "Please select party",
  AppStrings.reset: "Reset",
  AppStrings.orderCycle: "Order Cycle",
  AppStrings.add: "Add",
  AppStrings.invalidInputs: "Invalid inputs",
  AppStrings.totalStatsLog: "Total Stats Log:",
  AppStrings.viewCycles: "View Cycles",
  AppStrings.challan: "Challan",
  AppStrings.itemImage: "Item Image",
  AppStrings.selectOrCaptureAImage: "Select or Capture a Image",
  AppStrings.select: "Select",
  AppStrings.camera: "Camera",
  AppStrings.gallery: "Gallery",
  AppStrings.pleaseAddItemImage: "Please add item image",
  AppStrings.remove: "Remove",
  AppStrings.viewChallan: "View Challan",
  AppStrings.successfullyDownloadedAtDownloadFolder: "Successfully downloaded at 'Download' folder.",
  AppStrings.downloadFailedPleaseTryAgain: "Download failed, Please try again.",
  AppStrings.contact: "Contact",
  AppStrings.contactNumber: "Contact Number",
  AppStrings.enterContactNumber: "Enter contact number",
  AppStrings.pleaseEnterContactNumber: "Please enter contact number",
  AppStrings.editPartyDetails: "Edit Party Details",
  AppStrings.whatsappNotInstalled: "Whatsapp not installed",
  AppStrings.edit: "Edit",
  AppStrings.cancel: "Cancel",
  AppStrings.delete: "Delete",
  AppStrings.deletePartyText: "Are you sure? You want to delete 'Party'? After deleting all data will be lost under this party.",
  AppStrings.deleteItemText: "Are you sure? You want to delete 'Item'? After deleting all cycles will be lost under this order.",
  AppStrings.itemDetails: "Item Details",
  AppStrings.searchPvdColor: "Search pvd color",
  AppStrings.selectPvdColor: "Select pvd color",
  AppStrings.pleaseSelectPvdColor: "Please select pvd color",
  AppStrings.update: 'Update',
  AppStrings.newVersionAvailable: 'A new version is available. Please upgrade to it.',
  AppStrings.orderDate: 'Order date',
  AppStrings.challansAreNotGeneratedYet: 'Challans are not generated yet.',
  AppStrings.sortByParty: 'Sort by Party',
  AppStrings.sortByColor: 'Sort by Color',
  AppStrings.searchColor: 'Search color',
  AppStrings.editItemDetails: 'Edit Item Details',
  AppStrings.deleteCycleText: "Are you sure? You want to delete 'Cycle' cycle? After deleting cycle will be lost under this order.",
  AppStrings.description: "Description",
  AppStrings.enterDescription: "Enter description",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number",
  AppStrings.nowItemCantBeEditable: "Now, Item can't be editable",
  AppStrings.pleaseSelectAtLeastOneOrder: "Please selected at-least one order.",
  AppStrings.selectOrders: "Select orders",
  AppStrings.recycleBin: "Recycle Bin",
  AppStrings.notes: "Notes",
  AppStrings.creator: "Creator",
  AppStrings.thisIsLastBilledCycle: "This is last billed cycle.",
  AppStrings.sessionExpire: "Session Expire.",
  AppStrings.save: "Save",
  AppStrings.options: "Options",
  AppStrings.thisCycleIsDispatched: "This cycle is dispatched",
  AppStrings.challanNumber: "Receipt No.",
  AppStrings.pleaseEnterChallanNumber: "Please enter Receipt No.",
  AppStrings.selectCycles: "Select Cycles",
  AppStrings.pleaseSelectAtLeastOneCycle: "Please select at-least one cycle.",
  AppStrings.party: "Party",
  AppStrings.repair: "Repair",
  AppStrings.enterRepair: "Enter Repair",
  AppStrings.pleaseEnterValidRepair: "Please enter valid repair",
  AppStrings.generateChallan: "Generate Challan",
  AppStrings.pleaseEnterValidSize: "Please enter valid size",
  AppStrings.imageNotFound: "Image not found",
  AppStrings.pleaseSelectCategoryName: "Please select category name",
  AppStrings.categoryName: "Category Name",
  AppStrings.enterCategoryName: "Enter Category Name",
  AppStrings.ledger: "Ledger",
  AppStrings.ledgerInch: "Ledger (Inch)",
  AppStrings.generate: "Generate",
  AppStrings.repairingDetails: "Repairing Details",
  AppStrings.category: "Category",
  AppStrings.yesSure: "Yes, sure",
  AppStrings.areYouSureYouWantToExitCreateOrder: "Are you sure you want to exit create order?",
  AppStrings.areYouSureYouWantToGenerateChallan: "Are you sure you want to generate challan for this orders?",
  AppStrings.createdAt: "Created At",
  AppStrings.date: "Date",
  AppStrings.sr: "SR.",
  AppStrings.cat: "Cat.",
  AppStrings.item: "Item",
  AppStrings.inDate: "In Date",
  AppStrings.qty: "QTY",
  AppStrings.previous: "Previous",
  AppStrings.ok: "OK",
  AppStrings.wo: "W/O",
  AppStrings.inch: "Inch",
  AppStrings.totalInch: "Total C1 Inch",
  AppStrings.balanceQTY: "Balance QTY",
  AppStrings.open: "Open",
  AppStrings.amount: "Amount",
  AppStrings.totalAmount: "Total C1 Amount",
  AppStrings.selectPrinter: "Select Printer",
  AppStrings.pleaseSelectPrinter: "Please select printer",
  AppStrings.noPrinterFound: "No printer found",
  AppStrings.print: "Print",
  AppStrings.viewLedger: "View Ledger",
  AppStrings.startDate: "Start Date",
  AppStrings.pleaseSelectStartDate: "Please select start date",
  AppStrings.endDate: "End Date",
  AppStrings.pleaseSelectEndDate: "Please select end date",
  AppStrings.noChallanAvailableYet: "No challan available yet",
  AppStrings.totalInchCategories: "Total Inch Categories",
  AppStrings.totalAssetsCalculation: "Total Assets Calculation",
  AppStrings.urlCopied: "URL Copied",
  AppStrings.backup: "Backup",
  AppStrings.backupDownloadSuccess: "Backup downloaded successfully in \"Download\" folder!",
  AppStrings.somethingWentWrong: "Something went wrong",
  AppStrings.price: "Price",
  AppStrings.pr: "Pr.",
  AppStrings.deleteChallanText: "Are you sure? You want to delete 'Challan'? After deleting selected challan will be lost under this order.",
  AppStrings.selectChallan: "Select challan",
  AppStrings.pleaseSelectAtLeastOneChallan: "Please select at-least one challan.",
  AppStrings.account: "Account",
  AppStrings.paymentLedger: "Payment Ledger",
  AppStrings.orderSequence: "Order Sequence",
  AppStrings.searchItem: "Search Item",
  AppStrings.pleaseEnterDescription: "Please enter description",
  AppStrings.addPayment: "Add Payment",
  AppStrings.custom: "Custom",
  AppStrings.monthly: "Monthly",
  AppStrings.pendingPayment: "Pending Payment",
  AppStrings.paymentDetails: "Payment Details",
  AppStrings.reports: "Reports",
  AppStrings.employeesInMonth: "Employees In Month",
  AppStrings.categories: "Categories",
  AppStrings.searchCategory: "Search Category",
  AppStrings.reorderCategories: "Reorder Categories",
  AppStrings.addCategory: "Add Category",
  AppStrings.editCategory: "Edit Category",
  AppStrings.pleaseEnterCategoryName: "Please enter category name",
  AppStrings.pleaseEnterCategoryPrice: "Please enter category price",
  AppStrings.pleaseEnterValidCategoryPrice: "Please enter valid category price",
  AppStrings.pleaseEnterValidCategoryOrderNo: "Please enter valid category order no.",
  AppStrings.orderNo: "Order No.",
  AppStrings.pleaseEnterValidOrderNo: "Please enter valid order no.",
  AppStrings.categoryPrice: "Category Price",
  AppStrings.enterCategoryPrice: "Enter Category Price",
  AppStrings.cash: "Cash",
  AppStrings.online: "Online",
  AppStrings.onlinePatel: "Online (Patel)",
  AppStrings.onlineKevin: "Online (Kevin)",
  AppStrings.enterAmount: "Enter amount",
  AppStrings.pleaseEnterAmount: "Please enter amount",
  AppStrings.pleaseEnterValidaAmount: "Please enter valid amount",
  AppStrings.paymentMode: "Payment Mode",
  AppStrings.selectPaymentMode: "Select payment mode",
  AppStrings.pleaseSelectPaymentMode: "Please select payment mode",
  AppStrings.searchPaymentMode: "Search payment mode",
  AppStrings.getPayments: "Get Payments",
  AppStrings.noPaymentsFound: "No payments found",
  AppStrings.areYouSureYouWantToDeleteThisPayment: "Are you sure? You want to delete this Payment? After deleting selected payment will be lost under this party.",
  AppStrings.editPayment: "Edit Payment",
  AppStrings.employees: "Employees",
  AppStrings.january: "January",
  AppStrings.february: "February",
  AppStrings.march: "March",
  AppStrings.april: "April",
  AppStrings.may: "May",
  AppStrings.june: "June",
  AppStrings.july: "July",
  AppStrings.august: "August",
  AppStrings.september: "September",
  AppStrings.october: "October",
  AppStrings.november: "November",
  AppStrings.december: "December",
  AppStrings.month: "Month",
  AppStrings.selectMonth: "Select month",
  AppStrings.searchMonth: "Search month",
  AppStrings.pleaseSelectMonth: "Please select month",
  AppStrings.year: "Year",
  AppStrings.selectYear: "Select year",
  AppStrings.searchYear: "Search year",
  AppStrings.pleaseSelectYear: "Please select year",
  AppStrings.noOfEmployees: "No. of Employees",
  AppStrings.enterNoOfEmployees: "Enter No. of Employees",
  AppStrings.pleaseEnterNoOfEmployees: "Please enter no. of employees",
  AppStrings.noEmployeesDataFound: "No Employees Data Found",
  AppStrings.editNoOfEmployees: "Edit No. of Employees",
  AppStrings.completedInch: "Completed Inch",
  AppStrings.completedAmount: "Completed Amount",
  AppStrings.totalInvoiceAmount: "Total Invoice Amount",
  AppStrings.totalPaymentAmount: "Total Payment Amount",
  AppStrings.pendingAmount: "Pending Amount",
  AppStrings.payments: "Payments",
  AppStrings.invoices: "Invoices",
  AppStrings.viewPaymentLedger: "View Payment Ledger",
  AppStrings.closingBalance: "Closing Balance",
  AppStrings.openingBalance: "Opening Balance",
  AppStrings.noPendingPaymentsFound: "No pending payments found",
  AppStrings.totalPayment: "Total Payment",
  AppStrings.totalCompletedInch: "Total Completed Inch",
  AppStrings.totalCompletedAmount: "Total Completed Amount",
  AppStrings.selectRow: "Select Row",
  AppStrings.editRow: "Edit Row",
  AppStrings.billGST: "Bill (GST)",
  AppStrings.gstOptions: "GST Options",
  AppStrings.withKey: "With",
  AppStrings.without: "Without",
  AppStrings.sharePaymentLedger: "Share Payment Ledger",
  AppStrings.shareLedgerInvoice: "Share Ledger Invoice",
  AppStrings.shareInvoice: "Share Invoice",
};
