import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createOrder: "Create Order",
  AppStrings.itemName: "Item Name",
  AppStrings.enterItemName: "Enter item name",
  AppStrings.pleaseEnterItemName: "Please enter item name",
  AppStrings.pvdColor: "PVD Color",
  AppStrings.enterPVDColor: "Enter pvd color",
  AppStrings.pleaseEnterPVDColor: "Please enter pvd color",
  AppStrings.quantity: "Quantity",
  AppStrings.enterQuantity: "Enter quantity",
  AppStrings.pleaseEnterQuantity: "Please enter quantity",
  AppStrings.size: "Size",
  AppStrings.enterSize: "Enter size",
  AppStrings.pleaseEnterSize: "Please enter size",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "Enter ok pcs.",
  AppStrings.pleaseEnterOkPcs: "Please enter ok pcs.",
  AppStrings.rejected: "Rejected",
  AppStrings.enterRejected: "Enter rejected",
  AppStrings.pleaseEnterRejected: "Please enter rejected",
  AppStrings.pending: "Pending",
  AppStrings.enterPending: "Enter pending",
  AppStrings.pleaseEnterPending: "Please enter pending",
  AppStrings.orderDetails: "Order Details",
  AppStrings.woProcess: "W/O Process",
  AppStrings.enterWOProcess: "Enter w/o process",
  AppStrings.pleaseEnterWOProcess: "Please enter w/o process",
  AppStrings.partyName: "Party Name",
  AppStrings.enterPartyName: "Enter party name",
  AppStrings.pleaseEnterPartyName: "Please enter party name",
  AppStrings.searchParty: "Search party",
  AppStrings.selectParty: "Select party",
  AppStrings.pleaseSelectParty: "Please select party",
  AppStrings.reset: "Reset",
  AppStrings.orderCycle: "Order Cycle",
  AppStrings.add: "Add",
  AppStrings.invalidInputs: "Invalid inputs",
  AppStrings.lastCycleLog: "Last Cycle Log:",
  AppStrings.viewCycles: "View Cycles",
};
