import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.itemName: "આઇટમનું નામ",
  AppStrings.enterItemName: "આઇટમનું નામ દાખલ કરો",
  AppStrings.pleaseEnterItemName: "કૃપા કરીને આઇટમનું નામ દાખલ કરો",
  AppStrings.pvdColor: "PVD રંગ",
  AppStrings.enterPVDColor: "PVD રંગ દાખલ કરો",
  AppStrings.pleaseEnterPVDColor: "કૃપા કરીને PVD રંગ દાખલ કરો",
  AppStrings.quantity: "જથ્થો",
  AppStrings.enterQuantity: "જથ્થો દાખલ કરો",
  AppStrings.pleaseEnterQuantity: "કૃપા કરીને જથ્થો દાખલ કરો",
  AppStrings.size: "કદ",
  AppStrings.enterSize: "કદ દાખલ કરો",
  AppStrings.pleaseEnterSize: "કૃપા કરીને કદ દાખલ કરો",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "OK Pcs. દાખલ કરો",
  AppStrings.pleaseEnterOkPcs: "કૃપા કરીને ok pcs. દાખલ કરો",
  AppStrings.rejected: "રિજેકટેડ",
  AppStrings.enterRejected: "રિજેકટેડ દાખલ કરો",
  AppStrings.pleaseEnterRejected: "કૃપા કરીને રિજેકટેડ દાખલ કરો",
  AppStrings.pending: "બાકી છે",
  AppStrings.enterPending: "બાકી દાખલ કરો",
  AppStrings.pleaseEnterPending: "કૃપા કરીને બાકી દાખલ કરો",
  AppStrings.orderDetails: "ઓર્ડરની વિગતો",
  AppStrings.woProcess: "પ્રક્રિયા વિના",
  AppStrings.enterWOProcess: "પ્રક્રિયા વિના દાખલ કરો",
  AppStrings.pleaseEnterWOProcess: "કૃપા કરીને પ્રક્રિયા વિના દાખલ કરો",
  AppStrings.partyName: "પાર્ટીનું નામ",
  AppStrings.enterPartyName: "પાર્ટીનું નામ દાખલ કરો",
  AppStrings.pleaseEnterPartyName: "કૃપા કરીને પાર્ટીનું નામ દાખલ કરો",
  AppStrings.searchParty: "પાર્ટી શોધો",
  AppStrings.selectParty: "પાર્ટી પસંદ કરો",
  AppStrings.pleaseSelectParty: "કૃપા કરીને પાર્ટી પસંદ કરો",
  AppStrings.reset: "રીસેટ",
  AppStrings.orderCycle: "ઓર્ડર સાયકલ",
  AppStrings.add: "ઉમેરો",
  AppStrings.invalidInputs: "અમાન્ય ઇનપુટ્સ",
  AppStrings.lastCycleLog: "છેલ્લો સાયકલ લોગ:",
  AppStrings.viewCycles: "સાયકલ જુઓ",
  AppStrings.challan: "ચલણ",
  AppStrings.itemImage: "આઇટમની છબી",
  AppStrings.selectOrCaptureAImage: "છબી પસંદ કરો અથવા કેપ્ચર કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.camera: "કેમેરા",
  AppStrings.gallery: "ગેલેરી",
  AppStrings.pleaseAddItemImage: "કૃપા કરીને આઇટમની છબી ઉમેરો",
  AppStrings.remove: "નાપસંદ કરો",
  AppStrings.viewChallan: "ચલણ જુઓ",
};
