import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.itemName: "આઇટમનું નામ",
  AppStrings.enterItemName: "આઇટમનું નામ દાખલ કરો",
  AppStrings.pleaseEnterItemName: "કૃપા કરીને આઇટમનું નામ દાખલ કરો",
  AppStrings.pvdColor: "PVD રંગ",
  AppStrings.enterPVDColor: "PVD રંગ દાખલ કરો",
  AppStrings.pleaseEnterPVDColor: "કૃપા કરીને PVD રંગ દાખલ કરો",
  AppStrings.quantity: "જથ્થો",
  AppStrings.enterQuantity: "જથ્થો દાખલ કરો",
  AppStrings.pleaseEnterQuantity: "કૃપા કરીને જથ્થો દાખલ કરો",
  AppStrings.size: "કદ",
  AppStrings.enterSize: "કદ દાખલ કરો",
  AppStrings.pleaseEnterSize: "કૃપા કરીને કદ દાખલ કરો",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "OK Pcs. દાખલ કરો",
  AppStrings.pleaseEnterOkPcs: "કૃપા કરીને ok pcs. દાખલ કરો",
  AppStrings.rejected: "રિજેકટેડ",
  AppStrings.enterRejected: "રિજેકટેડ દાખલ કરો",
  AppStrings.pleaseEnterRejected: "કૃપા કરીને રિજેકટેડ દાખલ કરો",
  AppStrings.pending: "બાકી છે",
  AppStrings.enterPending: "બાકી દાખલ કરો",
  AppStrings.pleaseEnterPending: "કૃપા કરીને બાકી દાખલ કરો",
  AppStrings.orderDetails: "ઓર્ડરની વિગતો",
  AppStrings.woProcess: "પ્રક્રિયા વિના",
  AppStrings.enterWOProcess: "પ્રક્રિયા વિના દાખલ કરો",
  AppStrings.pleaseEnterWOProcess: "કૃપા કરીને પ્રક્રિયા વિના દાખલ કરો",
  AppStrings.partyName: "પાર્ટીનું નામ",
  AppStrings.enterPartyName: "પાર્ટીનું નામ દાખલ કરો",
  AppStrings.pleaseEnterPartyName: "કૃપા કરીને પાર્ટીનું નામ દાખલ કરો",
  AppStrings.searchParty: "પાર્ટી શોધો",
  AppStrings.selectParty: "પાર્ટી પસંદ કરો",
  AppStrings.pleaseSelectParty: "કૃપા કરીને પાર્ટી પસંદ કરો",
  AppStrings.reset: "રીસેટ",
  AppStrings.orderCycle: "ઓર્ડર સાયકલ",
  AppStrings.add: "ઉમેરો",
  AppStrings.invalidInputs: "અમાન્ય ઇનપુટ્સ",
  AppStrings.totalStatsLog: "કુલ આંકડા લોગ:",
  AppStrings.viewCycles: "સાયકલ જુઓ",
  AppStrings.challan: "ચલણ",
  AppStrings.itemImage: "આઇટમની છબી",
  AppStrings.selectOrCaptureAImage: "છબી પસંદ કરો અથવા કેપ્ચર કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.camera: "કેમેરા",
  AppStrings.gallery: "ગેલેરી",
  AppStrings.pleaseAddItemImage: "કૃપા કરીને આઇટમની છબી ઉમેરો",
  AppStrings.remove: "નાપસંદ કરો",
  AppStrings.viewChallan: "ચલણ જુઓ",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' ફોલ્ડર પર સફળતાપૂર્વક ડાઉનલોડ કર્યું.",
  AppStrings.downloadFailedPleaseTryAgain: "ડાઉનલોડ નિષ્ફળ થયું, કૃપા કરીને ફરી પ્રયાસ કરો.",
  AppStrings.contact: "સંપર્ક",
  AppStrings.contactNumber: "સંપર્ક નંબર",
  AppStrings.enterContactNumber: "સંપર્ક નંબર દાખલ કરો",
  AppStrings.pleaseEnterContactNumber: "કૃપા કરીને સંપર્ક નંબર દાખલ કરો",
  AppStrings.editPartyDetails: "કૃપા કરીને સંપર્ક નંબર દાખલ કરો",
  AppStrings.whatsappNotInstalled: "'Whatsapp' ઇન્સ્ટોલ કરેલ નથી",
  AppStrings.edit: "સંપાદિત કરો",
  AppStrings.cancel: "રદ કરો",
  AppStrings.delete: "કાઢી નાખો",
  AppStrings.deletePartyText: "શું તમને ખાતરી છે? તમે 'Party' કાઢી નાખવા માંગો છો? ડિલીટ કર્યા પછી આ પાર્ટી હેઠળ તમામ ડેટા ખોવાઈ જશે.",
  AppStrings.deleteItemText: "શું તમને ખાતરી છે? તમે 'Item' કાઢી નાખવા માંગો છો? ડિલીટ કર્યા પછી આ ઓર્ડર હેઠળ તમામ સાઈકલ ગુમ થઈ જશે.",
  AppStrings.itemDetails: "આઇટમની વિગતો",
  AppStrings.searchPvdColor: "PVD રંગ શોધો",
  AppStrings.selectPvdColor: "PVD રંગ પસંદ કરો",
  AppStrings.pleaseSelectPvdColor: "કૃપા કરીને PVD રંગ પસંદ કરો",
  AppStrings.update: 'અપડેટ કરો',
  AppStrings.newVersionAvailable: 'નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.',
  AppStrings.orderDate: 'ઓર્ડર તારીખ',
  AppStrings.challansAreNotGeneratedYet: 'ચલણ હજુ જનરેટ થયા નથી.',
  AppStrings.sortByParty: 'પાર્ટી દ્વારા સૉર્ટ કરો',
  AppStrings.sortByColor: 'રંગ દ્વારા સૉર્ટ કરો',
  AppStrings.searchColor: 'રંગ શોધો',
  AppStrings.editItemDetails: 'આઇટમ વિગતો સંપાદિત કરો',
  AppStrings.deleteCycleText: "શું તમને ખાતરી છે? તમે 'Cycle' સાયકલ કાઢી નાખવા માંગો છો? ડિલીટ કર્યા પછી આ ઓર્ડર હેઠળ સાયકલ ગુમ થઈ જશે.",
  AppStrings.description: "વર્ણન",
  AppStrings.enterDescription: "વર્ણન દાખલ કરો",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો",
  AppStrings.nowItemCantBeEditable: "હવે, આઇટમ સંપાદનયોગ્ય હોઈ શકતી નથી",
  AppStrings.pleaseSelectAtLeastOneOrder: "કૃપા કરીને ઓછામાં ઓછો એક ઓર્ડર પસંદ કરો.",
  AppStrings.selectOrders: "ઓર્ડર પસંદ કરો",
  AppStrings.recycleBin: "રિસાયકલ બિન",
  AppStrings.notes: "નોંધો",
  AppStrings.creator: "સર્જક",
  AppStrings.thisIsLastBilledCycle: "છેલ્લી આ સાયકલનું બિલ છે.",
  AppStrings.sessionExpire: "સત્ર સમાપ્ત.",
  AppStrings.save: "સાચવો",
  AppStrings.options: "વિકલ્પો",
  AppStrings.thisCycleIsDispatched: "આ સાયકલ રવાના થાય છે.",
  AppStrings.challanNumber: "ચલણ નં.",
  AppStrings.pleaseEnterChallanNumber: "કૃપા કરીને ચલણ નંબર દાખલ કરો.",
  AppStrings.selectCycles: "સાયકલ પસંદ કરો",
  AppStrings.pleaseSelectAtLeastOneCycle: "કૃપા કરીને ઓછામાં ઓછી એક સાયકલ પસંદ કરો.",
  AppStrings.party: "પાર્ટી",
  AppStrings.repair: "રિપેર",
  AppStrings.enterRepair: "રિપેર દાખલ કરો",
  AppStrings.pleaseEnterValidRepair: "કૃપા કરીને માન્ય રિપેર દાખલ કરો",
  AppStrings.generateChallan: "ચલાન બનાવો",
  AppStrings.pleaseEnterValidSize: "કૃપા કરીને માન્ય સાઈઝ દાખલ કરો",
  AppStrings.imageNotFound: "ઈમેજ મળી નહીં",
  AppStrings.pleaseSelectCategoryName: "કૃપા કરીને કેટેગરી નામ પસંદ કરો",
  AppStrings.categoryName: "કેટેગરી નામ",
  AppStrings.enterCategoryName: "કેટેગરી નામ દાખલ કરો",
  AppStrings.ledger: "લેજર",
  AppStrings.ledgerInch: "લેજર (ઇંચ)",
  AppStrings.generate: "જનરેટ કરો",
  AppStrings.repairingDetails: "રિપેરિંગ વિગતો",
  AppStrings.category: "શ્રેણી",
  AppStrings.yesSure: "હા, ખાતરીથી",
  AppStrings.areYouSureYouWantToExitCreateOrder: "શું તમે ઓર્ડર બનાવવાનું છોડવા માંગો છો?",
  AppStrings.areYouSureYouWantToGenerateChallan: "શું તમે આ ઓર્ડર માટે ચલણ બનાવવા માંગો છો?",
  AppStrings.createdAt: "બનાવ્યું તારીખે",
  AppStrings.date: "તારીખ",
  AppStrings.sr: "ક્રમ",
  AppStrings.cat: "શ્રે.",
  AppStrings.item: "વસ્તુ",
  AppStrings.inDate: "ઇન તારીખ",
  AppStrings.qty: "જથ્થો",
  AppStrings.previous: "પાછળનું",
  AppStrings.ok: "બરાબર",
  AppStrings.wo: "W/O",
  AppStrings.inch: "ઇંચ",
  AppStrings.totalInch: "કુલ C1 ઇંચ",
  AppStrings.balanceQTY: "બાકી જથ્થો",
  AppStrings.open: "ખુલ્લું",
  AppStrings.amount: "રકમ",
  AppStrings.totalAmount: "કુલ C1 રકમ",
  AppStrings.selectPrinter: "પ્રિન્ટર પસંદ કરો",
  AppStrings.pleaseSelectPrinter: "કૃપા કરીને પ્રિન્ટર પસંદ કરો",
  AppStrings.noPrinterFound: "કોઈ પ્રિન્ટર મળ્યો નથી",
  AppStrings.print: "પ્રિન્ટ કરો",
  AppStrings.viewLedger: "લેજર જુઓ",
  AppStrings.startDate: "શરૂઆત તારીખ",
  AppStrings.pleaseSelectStartDate: "કૃપા કરીને શરૂઆત તારીખ પસંદ કરો",
  AppStrings.endDate: "અંત તારીખ",
  AppStrings.pleaseSelectEndDate: "કૃપા કરીને અંત તારીખ પસંદ કરો",
  AppStrings.noChallanAvailableYet: "હજુ સુધી કોઈ ચલણ ઉપલબ્ધ નથી",
  AppStrings.totalInchCategories: "કુલ ઇંચ કેટેગરીઝ",
  AppStrings.totalAssetsCalculation: "કુલ સંપત્તિ ગણતરી",
  AppStrings.urlCopied: "URL કૉપિ થઈ ગયું",
  AppStrings.backup: "બેકઅપ",
  AppStrings.backupDownloadSuccess: "\"Download\" ફોલ્ડરમાં બેકઅપ સફળતાપૂર્વક ડાઉનલોડ થયું!",
  AppStrings.somethingWentWrong: "કૈંક તો ખોટું થયું",
};
