import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.itemName: "आइटम नाम",
  AppStrings.enterItemName: "आइटम का नाम दर्ज करें",
  AppStrings.pleaseEnterItemName: "कृपया आइटम का नाम दर्ज करें",
  AppStrings.pvdColor: "PVD रंग",
  AppStrings.enterPVDColor: "PVD रंग दर्ज करें",
  AppStrings.pleaseEnterPVDColor: "कृपया PVD रंग दर्ज करें",
  AppStrings.quantity: "मात्रा",
  AppStrings.enterQuantity: "मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.size: "आकार",
  AppStrings.enterSize: "आकार दर्ज करें",
  AppStrings.pleaseEnterSize: "कृपया आकार दर्ज करें",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "OK Pcs. दर्ज करें",
  AppStrings.pleaseEnterOkPcs: "कृपया ok pcs. दर्ज करें",
  AppStrings.rejected: "रिजेक्टेड",
  AppStrings.enterRejected: "रिजेक्टेड दर्ज करें",
  AppStrings.pleaseEnterRejected: "कृपया रिजेक्टेड दर्ज करें",
  AppStrings.pending: "लंबित",
  AppStrings.enterPending: "लंबित दर्ज करें",
  AppStrings.pleaseEnterPending: "कृपया लंबित दर्ज करें",
};
