import 'package:cph_stocks/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.itemName: "आइटम नाम",
  AppStrings.enterItemName: "आइटम का नाम दर्ज करें",
  AppStrings.pleaseEnterItemName: "कृपया आइटम का नाम दर्ज करें",
  AppStrings.pvdColor: "PVD रंग",
  AppStrings.enterPVDColor: "PVD रंग दर्ज करें",
  AppStrings.pleaseEnterPVDColor: "कृपया PVD रंग दर्ज करें",
  AppStrings.quantity: "मात्रा",
  AppStrings.enterQuantity: "मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.size: "आकार",
  AppStrings.enterSize: "आकार दर्ज करें",
  AppStrings.pleaseEnterSize: "कृपया आकार दर्ज करें",
  AppStrings.okPcs: "OK Pcs.",
  AppStrings.enterOkPcs: "OK Pcs. दर्ज करें",
  AppStrings.pleaseEnterOkPcs: "कृपया ok pcs. दर्ज करें",
  AppStrings.rejected: "रिजेक्टेड",
  AppStrings.enterRejected: "रिजेक्टेड दर्ज करें",
  AppStrings.pleaseEnterRejected: "कृपया रिजेक्टेड दर्ज करें",
  AppStrings.pending: "लंबित",
  AppStrings.enterPending: "लंबित दर्ज करें",
  AppStrings.pleaseEnterPending: "कृपया लंबित दर्ज करें",
  AppStrings.orderDetails: "ऑर्डर का विवरण",
  AppStrings.woProcess: "प्रक्रिया के बिना",
  AppStrings.enterWOProcess: "बिना प्रक्रिया के प्रवेश करें",
  AppStrings.pleaseEnterWOProcess: "कृपया बिना प्रक्रिया दर्ज करें",
  AppStrings.partyName: "पार्टी का नाम",
  AppStrings.enterPartyName: "पार्टी का नाम दर्ज करें",
  AppStrings.pleaseEnterPartyName: "कृपया पार्टी का नाम दर्ज करें",
  AppStrings.searchParty: "पार्टी खोजें",
  AppStrings.selectParty: "पार्टी का चयन करें",
  AppStrings.pleaseSelectParty: "कृपया पार्टी का चयन करें",
  AppStrings.reset: "रीसेट",
  AppStrings.orderCycle: "ऑर्डर चक्र",
  AppStrings.add: "जोड़ना",
  AppStrings.invalidInputs: "अमान्य इनपुट",
  AppStrings.totalStatsLog: "कुल आँकड़े लॉग:",
  AppStrings.challan: "चलान",
  AppStrings.itemImage: "आइटम छवि",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.pleaseAddItemImage: "कृपया आइटम छवि जोड़ें",
  AppStrings.remove: "चयन हटाएँं",
  AppStrings.viewChallan: "चलान देखें",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.contact: "संपर्क",
  AppStrings.contactNumber: "संपर्क नंबर",
  AppStrings.enterContactNumber: "संपर्क नंबर दर्ज करें",
  AppStrings.pleaseEnterContactNumber: "कृपया संपर्क नंबर दर्ज करें",
  AppStrings.editPartyDetails: "कृपया संपर्क नंबर दर्ज करें",
  AppStrings.whatsappNotInstalled: "'Whatsapp' इंस्टॉल नहीं है",
  AppStrings.edit: "संपादन करना",
  AppStrings.cancel: "रद्द करना",
  AppStrings.delete: "मिटाना",
  AppStrings.deletePartyText: "क्या आपको यकीन है? आप 'Party' हटाना चाहते हैं? डिलीट करने के बाद इस पार्टी के अंतर्गत सारा डेटा खो जाएगा।",
  AppStrings.deleteItemText: "क्या आपको यकीन है? आप 'Item' हटाना चाहते हैं? हटाने के बाद इस आदेश के तहत सभी चक्र खो जाएंगे।",
  AppStrings.itemDetails: "आइटम विवरण",
  AppStrings.searchPvdColor: "PVD रंग खोजें",
  AppStrings.selectPvdColor: "PVD रंग चुनें",
  AppStrings.pleaseSelectPvdColor: "कृपया PVD रंग चुनें",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.orderDate: 'आर्डर की तारीख',
  AppStrings.challansAreNotGeneratedYet: 'अभी चलान जनरेट नहीं हुए हैं।',
  AppStrings.sortByParty: 'पार्टी के अनुसार क्रमबद्ध करें',
  AppStrings.sortByColor: 'रंग के अनुसार क्रमबद्ध करें',
  AppStrings.searchColor: 'रंग खोजें',
  AppStrings.editItemDetails: 'आइटम विवरण संपादित करें',
  AppStrings.deleteCycleText: "क्या आपको यकीन है? आप 'साइकिल' चक्र को हटाना चाहते हैं? इस आदेश के तहत डिलीट करने के बाद चक्र नष्ट हो जाएगा।",
  AppStrings.description: "विवरण",
  AppStrings.enterDescription: "विवरण दर्ज करें",
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध फोन नंबर डालें",
  AppStrings.nowItemCantBeEditable: "अब, आइटम संपादन योग्य नहीं हो सकता",
  AppStrings.pleaseSelectAtLeastOneOrder: "कृपया कम से कम एक ऑर्डर चुनें।",
  AppStrings.selectOrders: "ऑर्डर चुनें",
  AppStrings.recycleBin: "रीसायकल बिन",
  AppStrings.notes: "टिप्पणियाँ",
  AppStrings.creator: "निर्माता",
  AppStrings.thisIsLastBilledCycle: "आखिरी है साइकिल का बिल।",
  AppStrings.sessionExpire: "सत्र समाप्ति।",
  AppStrings.options: "विकल्प",
  AppStrings.thisCycleIsDispatched: "यह साइकिल भेजा गया है।",
  AppStrings.challanNumber: "चालान नं.",
  AppStrings.pleaseEnterChallanNumber: "कृपया चालान नंबर दर्ज करें.",
  AppStrings.selectCycles: "साइकिल चुनें",
  AppStrings.pleaseSelectAtLeastOneCycle: "कृपया कम से कम एक साइकिल चुनें।",
  AppStrings.party: "पार्टी",
  AppStrings.repair: "मरम्मत",
  AppStrings.enterRepair: "मरम्मत दर्ज करें",
  AppStrings.pleaseEnterValidRepair: "कृपया मान्य मरम्मत दर्ज करें",
  AppStrings.generateChallan: "चालान बनाएँ",
  AppStrings.pleaseEnterValidSize: "कृपया मान्य आकार दर्ज करें",
  AppStrings.imageNotFound: "छवि नहीं मिली",
  AppStrings.pleaseSelectCategoryName: "कृपया श्रेणी नाम चुनें।",
  AppStrings.categoryName: "श्रेणी नाम",
  AppStrings.enterCategoryName: "श्रेणी नाम दर्ज करें",
  AppStrings.ledger: "लेज़र",
  AppStrings.ledgerInch: "लेज़र (इंच)",
  AppStrings.generate: "जनरेट करें",
  AppStrings.repairingDetails: "मरम्मत विवरण",
  AppStrings.category: "श्रेणी",
  AppStrings.yesSure: "हाँ, ज़रूर",
  AppStrings.areYouSureYouWantToExitCreateOrder: "क्या आप वाकई ऑर्डर बनाना छोड़ना चाहते हैं?",
  AppStrings.areYouSureYouWantToGenerateChallan: "क्या आप वाकई इस ऑर्डर का चालान बनाना चाहते हैं?",
  AppStrings.createdAt: "निर्मित तिथि",
  AppStrings.date: "तारीख",
  AppStrings.sr: "क्रम.",
  AppStrings.cat: "श्रे.",
  AppStrings.item: "आइटम",
  AppStrings.inDate: "इन तारीख",
  AppStrings.qty: "मात्रा",
  AppStrings.previous: "पिछला",
  AppStrings.ok: "ठीक है",
  AppStrings.wo: "W/O",
  AppStrings.inch: "इंच",
  AppStrings.totalInch: "कुल C1 इंच",
  AppStrings.balanceQTY: "बकाया मात्रा",
  AppStrings.open: "खुला",
  AppStrings.amount: "राशि",
  AppStrings.totalAmount: "कुल C1 राशि",
  AppStrings.selectPrinter: "प्रिंटर चुनें",
  AppStrings.pleaseSelectPrinter: "कृपया प्रिंटर चुनें",
  AppStrings.noPrinterFound: "कोई प्रिंटर नहीं मिला",
  AppStrings.print: "प्रिंट करें",
  AppStrings.viewLedger: "खाता देखें",
  AppStrings.startDate: "प्रारंभ तिथि",
  AppStrings.pleaseSelectStartDate: "कृपया प्रारंभ तिथि चुनें",
  AppStrings.endDate: "अंतिम तिथि",
  AppStrings.pleaseSelectEndDate: "कृपया अंतिम तिथि चुनें",
  AppStrings.noChallanAvailableYet: "अभी तक कोई चालान उपलब्ध नहीं है",
  AppStrings.totalInchCategories: "कुल इंच श्रेणियाँ",
  AppStrings.totalAssetsCalculation: "कुल संपत्ति गणना",
  AppStrings.urlCopied: "URL कॉपी हो गया",
  AppStrings.backup: "बैकअप",
  AppStrings.backupDownloadSuccess: "\"Download\" फ़ोल्डर में बैकअप सफलतापूर्वक डाउनलोड हुआ!",
  AppStrings.somethingWentWrong: "कुछ गलत हो गया",
  AppStrings.price: "कीमत",
  AppStrings.pr: "की.",
  AppStrings.deleteChallanText: "क्या आप सुनिश्चित हैं? आप 'चालान' हटाना चाहते हैं? हटाने के बाद, चयनित चालान इस ऑर्डर के अंतर्गत खो जाएगा।",
  AppStrings.selectChallan: "चालान चुनें",
  AppStrings.pleaseSelectAtLeastOneChallan: "कृपया कम से कम एक चालान चुनें।",
  AppStrings.account: "खाता",
  AppStrings.paymentLedger: "भुगतान खाता-बही",
  AppStrings.orderSequence: "ऑर्डर क्रम",
  AppStrings.searchItem: "आइटम खोजें",
  AppStrings.pleaseEnterDescription: "कृपया विवरण दर्ज करें",
  AppStrings.addPayment: "भुगतान जोड़ें",
  AppStrings.custom: "कस्टम",
  AppStrings.monthly: "मासिक",
  AppStrings.pendingPayment: "बकाया भुगतान",
  AppStrings.paymentDetails: "भुगतान विवरण",
  AppStrings.reports: "रिपोर्ट्स",
  AppStrings.employeesInMonth: "महीने में कर्मचारी",
  AppStrings.categories: "श्रेणियाँ",
  AppStrings.searchCategory: "श्रेणी खोजें",
  AppStrings.reorderCategories: "श्रेणियाँ पुनः क्रमबद्ध करें",
  AppStrings.addCategory: "श्रेणी जोड़ें",
  AppStrings.editCategory: "श्रेणी संपादित करें",
  AppStrings.pleaseEnterCategoryName: "कृपया श्रेणी का नाम दर्ज करें",
  AppStrings.pleaseEnterCategoryPrice: "कृपया श्रेणी की कीमत दर्ज करें",
  AppStrings.pleaseEnterValidCategoryPrice: "कृपया मान्य श्रेणी की कीमत दर्ज करें",
  AppStrings.pleaseEnterValidCategoryOrderNo: "कृपया मान्य श्रेणी ऑर्डर नंबर दर्ज करें",
  AppStrings.orderNo: "ऑर्डर नं.",
  AppStrings.pleaseEnterValidOrderNo: "कृपया मान्य ऑर्डर नंबर दर्ज करें",
  AppStrings.categoryPrice: "श्रेणी की कीमत",
  AppStrings.enterCategoryPrice: "श्रेणी की कीमत दर्ज करें",
  AppStrings.cash: "नकद",
  AppStrings.online: "ऑनलाइन",
  AppStrings.onlinePatel: "ऑनलाइन (पटेल)",
  AppStrings.onlineKevin: "ऑनलाइन (केविन)",
  AppStrings.enterAmount: "राशि दर्ज करें",
  AppStrings.pleaseEnterAmount: "कृपया राशि दर्ज करें",
  AppStrings.pleaseEnterValidaAmount: "कृपया मान्य राशि दर्ज करें",
  AppStrings.paymentMode: "भुगतान का तरीका",
  AppStrings.selectPaymentMode: "भुगतान का तरीका चुनें",
  AppStrings.pleaseSelectPaymentMode: "कृपया भुगतान का तरीका चुनें",
  AppStrings.searchPaymentMode: "भुगतान का तरीका खोजें",
  AppStrings.getPayments: "भुगतान प्राप्त करें",
  AppStrings.noPaymentsFound: "कोई भुगतान नहीं मिला",
  AppStrings.areYouSureYouWantToDeleteThisPayment: "क्या आप सुनिश्चित हैं? आप इस भुगतान को हटाना चाहते हैं? हटाने के बाद, चयनित भुगतान पार्टी के अंतर्गत खो जाएगा।",
  AppStrings.editPayment: "भुगतान संपादित करें",
  AppStrings.employees: "कर्मचारी",
  AppStrings.january: "जनवरी",
  AppStrings.february: "फरवरी",
  AppStrings.march: "मार्च",
  AppStrings.april: "अप्रैल",
  AppStrings.may: "मई",
  AppStrings.june: "जून",
  AppStrings.july: "जुलाई",
  AppStrings.august: "अगस्त",
  AppStrings.september: "सितंबर",
  AppStrings.october: "अक्टूबर",
  AppStrings.november: "नवंबर",
  AppStrings.december: "दिसंबर",
  AppStrings.month: "महीना",
  AppStrings.selectMonth: "महीना चुनें",
  AppStrings.searchMonth: "महीना खोजें",
  AppStrings.pleaseSelectMonth: "कृपया महीना चुनें",
  AppStrings.year: "वर्ष",
  AppStrings.selectYear: "वर्ष चुनें",
  AppStrings.searchYear: "वर्ष खोजें",
  AppStrings.pleaseSelectYear: "कृपया वर्ष चुनें",
  AppStrings.noOfEmployees: "कर्मचारियों की संख्या",
  AppStrings.enterNoOfEmployees: "कर्मचारियों की संख्या दर्ज करें",
  AppStrings.pleaseEnterNoOfEmployees: "कृपया कर्मचारियों की संख्या दर्ज करें",
  AppStrings.noEmployeesDataFound: "कोई कर्मचारी डेटा नहीं मिला",
  AppStrings.editNoOfEmployees: "कर्मचारियों की संख्या संपादित करें",
  AppStrings.completedInch: "पूर्ण इंच",
  AppStrings.completedAmount: "पूर्ण राशि",
  AppStrings.totalInvoiceAmount: "कुल चालान राशि",
  AppStrings.totalPaymentAmount: "कुल भुगतान राशि",
  AppStrings.pendingAmount: "बकाया राशि",
  AppStrings.payments: "भुगतान",
  AppStrings.invoices: "चालान",
  AppStrings.viewPaymentLedger: "भुगतान खाता-बही देखें",
  AppStrings.closingBalance: "अंतिम शेष",
  AppStrings.openingBalance: "प्रारंभिक शेष",
  AppStrings.noPendingPaymentsFound: "कोई बकाया भुगतान नहीं मिला",
  AppStrings.totalPayment: "कुल भुगतान",
  AppStrings.totalCompletedInch: "कुल पूर्ण इंच",
  AppStrings.totalCompletedAmount: "कुल पूर्ण राशि",
};
