name: cph_stocks
description: "Stocks handle of CPH."
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  responsive_sizer: ^3.3.0+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_image_compress: ^2.2.0
  syncfusion_flutter_pdfviewer: ^25.1.35
  syncfusion_flutter_core: ^25.1.35
  whatsapp_share: ^2.0.2
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/