name: cph_stocks
description: "Stocks handle of CPH."
publish_to: 'none'

version: 2.1.16+68

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Widgets Libs
  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  font_awesome_flutter: ^10.10.0
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

  # State Management Lib
  get: ^4.7.2

  # Network Libs
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0

  # Storage Libs
  get_storage: ^2.1.1

  # Device & App Info Libs
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0

  # File Libs
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  share_plus: ^11.1.0
  mime: ^2.0.0

  # Quill Formation Libs
  flutter_quill: ^11.4.2
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.3

  # Printing Libs
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_core: ^31.1.17
  syncfusion_flutter_pdfviewer: ^31.1.17
  syncfusion_flutter_charts: ^31.1.17

dependency_overrides:
  intl: ^0.20.2
  pdf:
    git:
      url: https://github.com/Gustl22/dart_pdf.git
      path: pdf/
      ref: 313-column-span
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto/
    - assets/fonts/NotoSansSymbols2/
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#1D232A"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#1D232A"