name: cph_stocks
description: "Stocks handle of CPH."
publish_to: 'none'

version: 1.2.5+30

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  responsive_sizer: ^3.3.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dropdown_search: ^6.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.3.0
  syncfusion_flutter_core: ^27.1.53
  syncfusion_flutter_pdfviewer: ^27.1.53
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1

  # Quill Formation Libs
  flutter_quill: ^10.8.5
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/