name: cph_stocks
description: "Stocks handle of CPH."
publish_to: 'none'

version: 1.2.8+33

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Widgets Libs
  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_core: ^29.2.7
  syncfusion_flutter_pdfviewer: ^29.2.7
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

  # State Management Lib
  get: ^4.7.2

  # Network Libs
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1

  # Storage Libs
  get_storage: ^2.1.1

  # Device & App Info Libs
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0

  # File Libs
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  # Quill Formation Libs
  flutter_quill: ^11.4.1
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.2

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#1D232A"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#1D232A"