name: cph_stocks
description: "Stocks handle of CPH."
publish_to: 'none'

version: 1.2.8+33

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  responsive_sizer: ^3.3.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_core: ^28.2.12
  syncfusion_flutter_pdfviewer: ^28.2.12
  font_awesome_flutter: ^10.8.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.5
  path: ^1.9.0
  meta: ^1.15.0

  # Quill Formation Libs
  flutter_quill: ^11.1.1
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.0

dependency_overrides:
  path: ^1.9.1
  meta: ^1.16.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#1D232A"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#1D232A"